name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # for local run --  $ act -j build -P ubuntu-latest=nektos/act-environments-ubuntu:18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
         # for act caching download https://static.azul.com/zulu/bin/zulu11.43.21-ca-jdk11.0.9-linux_x64.tar.gz
         # to root workdir an uncomment
         #jdkFile: zulu11.43.21-ca-jdk11.0.9-linux_x64.tar.gz

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clone kefir
        uses: actions/checkout@v2
        with:
          repository: dmitry-weirdo/pda-kefir
          path: kefir
          # for local act  
          #token: 

      - name: Install kefir
        working-directory: kefir
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true --no-transfer-progress

      - name: Install kgparserSrv
        working-directory: kgparserSrv
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true --no-transfer-progress

      - name: Install root
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true --no-transfer-progress
      
      - name: Test kgparserSrv
        working-directory: kgparserSrv
        run: mvn test --no-transfer-progress
